apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    app: MyBigWebApp



apiVersion: v1
kind: Pod
metadata:
  name: pod-example
spec:
  containers:
  - name: nginx
    image: nginx:stable-alpine
    ports:
    - containerPort: 80
