apiVersion: v1
kind: ReplicationController
metadata:
  name: dev-int-monitor
  labels:
    type: dashing
    app: dev-int-monitor
spec:
  replicas: 1
  selector:
    app: dev-int-monitor
  template:
    metadata:
      name: dev-int-monitor
      labels:
        app: dev-int-monitor
    spec:
       containers:
         - image: registry.abc.com:443/mycompany/dashing:latest
           name: dashing-dev-int-container

           ports:
             - containerPort: 8080
               protocol: TCP
